### ISSUE TITLE
configuration improvement

### ISSUE THREAD

**Issue by ndfz** [ndfz/nvim#1]
### TODO:
- [ ] uninstall unnecessary plugins
- [ ] unclutter the lsp
- [ ] make the keymaps more comfortable
- [ ] make lspsettings more convenient
